FROM arm32v7/ubuntu:latest

MAINTAINER cade <cade.call@mediciventures.com>

EXPOSE $RPCPORT

EXPOSE $PORT

RUN useradd -ms /bin/bash aipg

RUN mkdir /etc/aipg

RUN mkdir /var/lib/aipg

RUN chown aipg:aipg /etc/aipg /var/lib/aipg

WORKDIR /home/aipg

COPY --chown=aipg:aipg linux64/* ./run.sh /home/aipg/

USER aipg

CMD ["/home/aipg/run.sh"]
